---
# Production Network Inventory - Enterprise Scale
all:
  children:
    cisco_devices:
      children:
        cisco_switches:
          hosts:
            # Core Switches (10 devices)
            sw-core-01:
              ansible_host: 10.0.1.10
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: core_switch
              site: datacenter_01
              stack_priority: 15
            sw-core-02:
              ansible_host: 10.0.1.11
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: core_switch
              site: datacenter_01
              stack_priority: 14
            sw-core-03:
              ansible_host: 10.0.1.12
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: core_switch
              site: datacenter_02
              stack_priority: 15
            sw-core-04:
              ansible_host: 10.0.1.13
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: core_switch
              site: datacenter_02
              stack_priority: 14
            sw-core-05:
              ansible_host: 10.0.1.14
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: core_switch
              site: branch_01
              stack_priority: 15
            sw-core-06:
              ansible_host: 10.0.1.15
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: core_switch
              site: branch_01
              stack_priority: 14
            sw-core-07:
              ansible_host: 10.0.1.16
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: core_switch
              site: branch_02
              stack_priority: 15
            sw-core-08:
              ansible_host: 10.0.1.17
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: core_switch
              site: branch_02
              stack_priority: 14
            sw-core-09:
              ansible_host: 10.0.1.18
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: core_switch
              site: remote_01
              stack_priority: 15
            sw-core-10:
              ansible_host: 10.0.1.19
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: core_switch
              site: remote_01
              stack_priority: 14

            # Distribution Switches (20 devices)
            sw-dist-01:
              ansible_host: 10.0.2.10
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: datacenter_01
            sw-dist-02:
              ansible_host: 10.0.2.11
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: datacenter_01
            sw-dist-03:
              ansible_host: 10.0.2.12
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: datacenter_02
            sw-dist-04:
              ansible_host: 10.0.2.13
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: datacenter_02
            sw-dist-05:
              ansible_host: 10.0.2.14
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: branch_01
            sw-dist-06:
              ansible_host: 10.0.2.15
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: branch_01
            sw-dist-07:
              ansible_host: 10.0.2.16
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: branch_02
            sw-dist-08:
              ansible_host: 10.0.2.17
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: branch_02
            sw-dist-09:
              ansible_host: 10.0.2.18
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: remote_01
            sw-dist-10:
              ansible_host: 10.0.2.19
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: remote_01
            sw-dist-11:
              ansible_host: 10.0.2.20
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: remote_02
            sw-dist-12:
              ansible_host: 10.0.2.21
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: remote_02
            sw-dist-13:
              ansible_host: 10.0.2.22
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: remote_03
            sw-dist-14:
              ansible_host: 10.0.2.23
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: remote_03
            sw-dist-15:
              ansible_host: 10.0.2.24
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: remote_04
            sw-dist-16:
              ansible_host: 10.0.2.25
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: remote_04
            sw-dist-17:
              ansible_host: 10.0.2.26
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: remote_05
            sw-dist-18:
              ansible_host: 10.0.2.27
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: remote_05
            sw-dist-19:
              ansible_host: 10.0.2.28
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: remote_06
            sw-dist-20:
              ansible_host: 10.0.2.29
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: distribution_switch
              site: remote_06

    palo_alto_devices:
      children:
        palo_alto_firewalls:
          hosts:
            fw-dmz-01:
              ansible_host: 10.0.1.50
              ansible_connection: local
              panos_username: "{{ vault_panos_username }}"
              panos_password: "{{ vault_panos_password }}"
              device_role: perimeter_firewall
              site: datacenter_01
              panos_provider:
                ip_address: "{{ ansible_host }}"
                username: "{{ panos_username }}"
                password: "{{ panos_password }}"

    fortinet_devices:
      children:
        fortinet_firewalls:
          hosts:
            fw-internal-01:
              ansible_host: 10.0.1.60
              ansible_connection: httpapi
              ansible_httpapi_use_ssl: true
              ansible_httpapi_port: 443
              ansible_httpapi_session_key: "{{ vault_fortigate_api_token }}"
              device_role: internal_firewall
              site: datacenter_01

    juniper_devices:
      children:
        juniper_routers:
          hosts:
            rtr-wan-01:
              ansible_host: 10.0.1.2
              ansible_network_os: junos
              ansible_connection: netconf
              ansible_user: "{{ vault_juniper_username }}"
              ansible_password: "{{ vault_juniper_password }}"
              device_role: wan_router
              site: datacenter_01
              bgp_asn: 65001

    arista_devices:
      children:
        arista_switches:
          hosts:
            sw-spine-01:
              ansible_host: 10.0.1.30
              ansible_network_os: eos
              ansible_connection: httpapi
              ansible_httpapi_use_ssl: true
              ansible_httpapi_port: 443
              ansible_user: "{{ vault_arista_username }}"
              ansible_password: "{{ vault_arista_password }}"
              device_role: spine_switch
              site: datacenter_01
