---
# Development inventory (mirrors production structure)
all:
  children:
    cisco_devices:
      children:
        cisco_switches:
          hosts:
            sw-dev-01:
              ansible_host: 10.0.100.10
              ansible_network_os: ios
              ansible_connection: network_cli
              ansible_user: "{{ vault_cisco_username }}"
              ansible_password: "{{ vault_cisco_password }}"
              device_role: development_switch
              site: lab

    palo_alto_devices:
      children:
        palo_alto_firewalls:
          hosts:
            fw-dev-01:
              ansible_host: 10.0.100.50
              ansible_connection: local
              panos_username: "{{ vault_panos_username }}"
              panos_password: "{{ vault_panos_password }}"
              device_role: development_firewall
              site: lab
