---
# Deploy security policies across network infrastructure
- name: Deploy security policies to firewalls
  hosts: palo_alto_firewalls
  gather_facts: false
  connection: local
  vars:
    provider: "{{ panos_provider }}"

  tasks:
  - name: Create address objects
    paloaltonetworks.panos.panos_address_object:
      provider: "{{ provider }}"
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      address_type: "{{ item.type }}"
      state: present
    loop: "{{ panos_address_objects }}"
    register: address_objects_result
    # Idempotent creation of address objects

  - name: Deploy security rules
    paloaltonetworks.panos.panos_security_rule:
      provider: "{{ provider }}"
      rule_name: "{{ item.rule_name }}"
      source_zone: "{{ item.source_zone }}"
      destination_zone: "{{ item.destination_zone }}"
      source_address: "{{ item.source_address }}"
      destination_address: "{{ item.destination_address }}"
      application: "{{ item.application }}"
      service: "{{ item.service }}"
      action: "{{ item.action }}"
      log_start: "{{ item.log_start | default(false) }}"
      log_end: "{{ item.log_end | default(true) }}"
      state: present
    loop: "{{ panos_security_policies }}"
    register: security_rules_result
    # Deploy all security policies from group_vars

  - name: Commit configuration changes
    paloaltonetworks.panos.panos_commit_push:
      provider: "{{ provider }}"
      description: "Ansible automated policy deployment - {{ ansible_date_time.iso8601 }}"
    when: address_objects_result.changed or security_rules_result.changed
    # Only commit if changes were made

- name: Deploy Fortinet firewall policies
  hosts: fortinet_firewalls
  gather_facts: false
  connection: httpapi

  tasks:
  - name: Configure address objects
    fortinet.fortios.fortios_firewall_address:
      state: present
      firewall_address:
        name: "{{ item.name }}"
        subnet: "{{ item.subnet }}"
        type: "{{ item.type }}"
    loop: "{{ fortinet_address_objects }}"
    register: fortinet_addresses_result
    # Create address objects for firewall policies

  - name: Deploy firewall policies
    fortinet.fortios.fortios_firewall_policy:
      state: present
      firewall_policy:
        policyid: "{{ item.policyid }}"
        name: "{{ item.name }}"
        srcintf: "{{ item.srcintf }}"
        dstintf: "{{ item.dstintf }}"
        srcaddr: "{{ item.srcaddr }}"
        dstaddr: "{{ item.dstaddr }}"
        service: "{{ item.service }}"
        action: "{{ item.action }}"
        schedule: "{{ item.schedule }}"
        logtraffic: "{{ item.logtraffic }}"
    loop: "{{ fortinet_firewall_policies }}"
    register: fortinet_policies_result
    # Deploy FortiGate policies

  - name: Display deployment summary
    ansible.builtin.debug:
      msg:
      - "Device: {{ inventory_hostname }}"
      - "Address objects processed: {{ fortinet_address_objects | length }}"
      - "Policies processed: {{ fortinet_firewall_policies | length }}"
      - "Changes made: {{ fortinet_addresses_result.changed or fortinet_policies_result.changed }}"
